
all:
	@echo "TODO: Populate help message with available targets."

#npm i -D jest ts-jest typescript @types/jest @types/node
#npx ts-jest config:init

run_tests:
	npx jest tests/CalculateCRC32.test.ts

